# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Whale-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Whale-iOS
  pod 'Alamofire' 
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'lottie-ios'
  pod 'SnapKit'
  pod 'Then'
end
